name: deploy to github pages
on:
  push:
    branches:
      - master
      - renewal
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true

      - name: export env
        run: export X_API_KEY=${{ secrets.X_API_KEY }}
      - name: install
        run: yarn
      - name: build
        run: |
          X_API_KEY=${{ secrets.X_API_KEY }} yarn run build
          touch out/.nojekyll
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
