name: deploy to github pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.1
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: build
        run: X_API_KEY=$X_API_KEY pnpm build
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
      - run: |
          touch ./out/.nojekyll
          touch ./out/CNAME
          echo 'minojiro.com' >> ./out/CNAME
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
